language: python
services:
- docker
dist: xenial
python:
- '2.7'
- '3.7'
before_install:
- docker pull eclipse-mosquitto
- docker run -d -p 11883:1883 -p 9001:9001 -v $(pwd)/mosquitto:/mosquitto/config eclipse-mosquitto
- docker run -d -p 1883:1883 eclipse-mosquitto
install:
- pip install -r requirements.txt
script:
- robot -P src tests
deploy:
  - provider: pypi
    user: __token__
    password: $PYPI_TOKEN
    distributions: sdist bdist_wheel
    skip_cleanup: true
    on:
      repo: randomsync/robotframework-mqttlibrary
      tags: true
  - provider: releases
    api_key:
      secure: JAaqldr74M3AwKBUAyCoeEdeFotPgXlSO7ML6IWpv327UXsz/CZyZg3lDnFZEPyUfzr/pndUEN/M/eeHTuLMXVhv5rdaiMWS5pXXcs6mmR7irT5LK3giRJKJpfNWcOTCRkotHJRkMC7vOuHWhuLrJ0a7v4yxZyTcqBsQUq+Qk/Q=
    file: dist/*
    skip_cleanup: true
    draft: true
    on:
      repo: randomsync/robotframework-mqttlibrary
      tags: true
      python: '3.7'
